const Fooditem = [
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS02OZYJ5byLHnwDmnhhRzGvaVAawOrXr8IKw&usqp=CAU",
      name:"Chapati",
      price:50,
      id:1
    },
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLzVyWo4_huGkKkX-IUR7EjocfBb9idtniVw&usqp=CAU",
      name:"Pickle",
      price:80,
      id:2
    },
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9hnnOu_lE8r6b4TZL7gwr7T0FDJJB4Ek8Qw&usqp=CAU",
      name:"Curd",
      price:70,
      id:3
    },
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9tqa-Aiy45wgmFmclvnzeagYUuqiZmqANVg&usqp=CAU",
      name:"Sweet",
      price:120,
      id:4
    },
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMDSUO8F83rzSGggrVpF2aHwFynt2CdIHX2w&usqp=CAU",
      name:"Dal",
      price:150,
      id:6
    },
    {
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtNTSlwfBRwdI1cINcrOX0DACzqc0fWsDwHQ&usqp=CAU",
      name:"Paneer",
      price:150,
      id:7
    }
  ]
  export default Fooditem;